import './globals.css';
import '@/styles/custom.css';

import { Suspense } from 'react';
import type { Metadata } from 'next';
import { Analytics } from '@vercel/analytics/react';
import DefaultLayout from '@/components/templates/DefaultLayout';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html>
            <head>
                <Suspense>
                    <meta name='keywords' content='' />
                </Suspense>
                <link rel='preconnect' href='https://fonts.googleapis.com' />
                <link rel='preconnect' href='https://fonts.gstatic.com' />
                <link
                    href='https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,700;1,400;1,700&amp;family=Noto+Sans+JP:wght@400;500;700&amp;display=swap'
                    rel='stylesheet'
                ></link>
            </head>
            <DefaultLayout>
                {children}
                <Analytics />
            </DefaultLayout>
        </html>
    );
}
